### PR TITLE
RLS 1.0.2

### PR DESCRIPTION
**Pull request by TomAugspurger**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by TomAugspurger** [comment]
@conda-forge-admin, please rerender

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Comment by TomAugspurger** [comment]
Any suggestions on the ppc64 failure? Seems to have timed out while compiling pandas.

We don't have any testing on power, so I'm probably not going to hold up the release for it.

**Comment by jreback** [comment]
would just skip /
ignore

maybe the rerender added?

**Pull request merged**
