### PR TITLE
RLS: 0.21.1

### PR DESCRIPTION
**Pull request by TomAugspurger**

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
The Mac packages on travis seem to have a rather long backlog, should we already merge this?

**Comment by TomAugspurger** [comment]
No preference. If I'm right, the mac packages at https://travis-ci.org/MacPython/pandas-wheels should start building in ~1.5-2 hours (based on how long NumPy's took to start).

**Comment by ocefpaf** [comment]
@TomAugspurger and @jorisvandenbossche I usually enable Travis-Ci on my own instance b/c that one will finishes before conda-forge's one. That way I can merge it knowing it will pass and without blocking the Linux and Windows packages. (Just a suggestion, you don't have to do this. The other alternative is to merge and keep an eye on master to see if there will be any failures on Travis-CI.)

**Comment by TomAugspurger** [comment]
Thanks @ocefpaf, I've done enabled my fork for next time :)

The builds at https://travis-ci.org/MacPython/pandas-wheels/builds/315339826 are running, so I'll merge once those pass.

**Pull request merged**
