### PR TITLE
Update checksum

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
See https://github.com/conda-forge/pandas-feedstock/pull/24#issuecomment-299743865

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
@TomAugspurger The command in our release docs (`curl https://github.com/pandas-dev/pandas/archive/v0.20.1.tar.gz | openssl dgst -sha256`) gives apparently the wrong sha:

```
joris@joris-XPS-13-9350:~/scipy/pandas-feedstock$ curl https://github.com/pandas-dev/pandas/archive/v0.20.1.tar.gz | openssl dgst -sha256
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   126    0   126    0     0    167      0 --:--:-- --:--:-- --:--:--   186
(stdin)= e85ac7194d28a450adda3195b7bfc839ac6f413a799022e2485e23ddee3846dd
```

while if I download manually:

```
joris@joris-XPS-13-9350:~/Downloads$ openssl dgst -sha256 pandas-0.20.1.tar.gz 
SHA256(pandas-0.20.1.tar.gz)= d9f67bb17f334ad395e01b2339c3756f3e0d0240cb94c094ef711bbfc5c56c80
```

**Comment by TomAugspurger** [comment]
Huh... I'll update the release docs.

FWIW, when I made the conda-forge PR originally, I'm pretty sure I did the manual download and then `openssl`. Could be wrong.

Thanks for making is PR.

**Comment by ocefpaf** [comment]
> FWIW, when I made the conda-forge PR originally, I'm pretty sure I did the manual download and then `openssl`. Could be wrong.

You probably did it correctly and that is why the Linux packages were uploaded correctly, I am guessing the checksum changed after that (Travis-CI and AppVeyor are slower and CircleCI).

GitHub **does** change the checksum sometimes. I guess that happens when people edit the release info for example.

**Comment by jorisvandenbossche** [comment]
Yes, we were actually talking about that to *not* edit the release notes to prevent this (there was a small error in it), but apparently it changed anyhow .. :-)

**Comment by ocefpaf** [comment]
Yeah, that is quite annoying :-(

I am starting to use the new PyPI (warehouse) URLs for most of my feedstocks now because the sha256 is provided via a link, and they don't change the tarball (nor the checksum) unless it is a new release.

**Comment by jorisvandenbossche** [comment]
The problem with pypi (but not sure if that will be the same with the new warehouse), is that you then already have to publish the source distributions, before you have binary packages uploaded as well. Which also gives (short-term) problems ..

**Comment by ocefpaf** [comment]
> The problem with pypi (but not sure if that will be the same with the new warehouse), is that you then already have to publish the source distributions, before you have binary packages uploaded as well

I believe that is still true :-(

**Pull request merged**
