### PR TITLE
remove duplicate url-key in recipe

### LINKED ISSUE #67: Duplicated key *url* in meta.yaml
When trying to process meta.yaml using ruamel_yaml it shows a error. It can be suppressed now, but it will become a real error in future. If you want to use several sources you have to use a list like that:
```
source:
  - url: <first url here>
    sha256: <checksum for the url above>
  - url: <second url here>
```
Otherwise YAML parsers raise DuplicatedKeyError or another exception with the same meaning.

### PR DESCRIPTION
**Pull request by h-vetinari**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Fixes #67. This duplicate key is at least one of the reasons why the auto-tickbot doesn't seem to be picking up PRs for this feedstock.

### CODE REVIEW

**Comment by h-vetinari** [comment]
@conda-forge-admin, please rerender

**Comment by h-vetinari** [comment]
Actually, I just saw that @mbargull had already quietly solved the ppc64le problem from #78 in #75. @xhochy 

I've tried cherry-picking his commit here. Hopefully that will allow us to go back to faster builds...

**Comment by TomAugspurger** [comment]
Need to bump the build number?

**Comment by h-vetinari** [comment]
> Need to bump the build number?

Since this changes nothing about the actual build, that is not necessary. But if you prefer, I can bump it.

**Comment by ocefpaf** [comment]
No need to bump.

**Pull request merged**
