### PR TITLE
Build packages for numpy 1.12

### PR DESCRIPTION
**Pull request by astaric**
Rerender feedstock to add numpy 1.12 to the build configuration.

I kept the build number the same as the recipe did not change.

### CODE REVIEW

**Comment by astaric** [comment]
The builds fail with a fun error (SHA256 mismatch).

Is there a specific reason this package downloads the source from github and not pypi? As far as I know, github creates arcives on the fly so there is no guarantee that the zips dowloaded at different times will be identical (even though they contain identical files), while pypi always serves the same archive.

**Comment by jorisvandenbossche** [comment]
See also https://github.com/conda-forge/pandas-feedstock/issues/18. For some reason the sha has changed since the initial release (possibly because I edited the release notes on github. The number *is* stable though, if you do not touch it). So you will just have to update this.

**Comment by astaric** [comment]
Done. I am still curious if the package url could be changed to point to pypi?

**Comment by jorisvandenbossche** [comment]
Regarding pypi vs github, not sure why, it was like that from the initial commit.

**Comment by ocefpaf** [comment]
> Regarding pypi vs github, not sure why, it was like that from the initial commit.

I prefer GitHub tarballs because it is closer to the source\* but at the end of the day it depends where the source is more up-to-date. In the pandas cases I guess both are pretty much OK.

\* By that I mean that some PyPI sources have more some extra elements that in conda-forge we should prepare manually instead of using them. That is usually true for packages that have `npm` stuff and pandas is not one of them.

**Comment by astaric** [comment]
Thanks for the explanation. In the past, I have encountered a package that installed correctly from PyPi but not from github (https://github.com/conda-forge/setuptools_scm-feedstock/pull/11) so I personally tend to prefer PyPI tarballs, but if both tarballs contain the same code, it does not matter.

**Comment by marscher** [comment]
Are git clones allowed? One could checkout a specific version tag, git ensures that the hashes are correct. Or does this violate some conda-forge policy?

**Comment by ocefpaf** [comment]
> Are git clones allowed? One could checkout a specific version tag, git ensures that the hashes are correct. Or does this violate some conda-forge policy?

We prefer the tarball to avoid cloning more that when is needed and reducing the CI time.

**Pull request merged**
