### PR TITLE
pandas v2.0.0rc0 (main branch)

### PR DESCRIPTION
**Pull request by datapythonista**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

Will rerender with the bot if needed.

### CODE REVIEW

**Comment by datapythonista** [comment]
@conda-forge-admin, please rerender

**Comment by datapythonista** [comment]
I'm not 100% sure what's going on, but seems like versioneer needs to have the config file (`pyproject.toml` I assume) available during the building of the conda packages, and seems like it's not. I checked some other packages, but I didn't find any that is using versioneer as a dependency to use as reference. If anyone understands the problem better or has any idea on how to fix this, that'd be helpful.

I'll continue tomorrow, it's late in Europe, but feel free to push to this PR.

**Comment by jorisvandenbossche** [comment]
Yeah, the error is confusing (I ran into it for another package as well), the problem is that the `versioneer` package doesn't depend on tomli as required dependency, but still needs it to function in pyproject.toml

**Comment by simonjayhawkins** [comment]
for the rc we used to merge to dev branch. I've not kept abreast of the build changes of late. Is the dev branch no longer used?

**Comment by jorisvandenbossche** [comment]
Ah, yes, that is indeed still needed (otherwise we would be releasing this as default for everyone already), good that you catch that!

**Comment by simonjayhawkins** [comment]
I don't think I ever had a good process, more of trial and error and help from Joris when things got complicated.

The goal is just to get the package to be published to a different channel. So merging in main to dev is the general idea.

**Comment by datapythonista** [comment]
Closing in favor of #155. I opened that PR to `dev`, copying `conda-forge.yml` and `recipe/meta.yml` from main with the release change, and re-rendered, and everything looks good (I guess we'll still have the arm failures we had here).

**Comment by jorisvandenbossche** [comment]
> dev seems to be quite outdated

Normally just from the last time we made an RC, so 1.5.0

I also don't have a fixed process, I think typically something like taking all things that get manually changed from the main branch and put that in the dev branch, and let the re-rendering do the rest. So basically what you did.

**Pull request closed without merging**
