### PR TITLE
RLS v0.21.0rc1

### PR DESCRIPTION
**Pull request by TomAugspurger**
Following the changes in https://github.com/conda-forge/matplotlib-feedstock/pull/128 for an RC

### CODE REVIEW

**Comment by TomAugspurger** [comment]
@conda-forge-admin, please rerender.

**Comment by TomAugspurger** [comment]
Ah, pandas updated the minimum version, and I needed to undo the changes in https://github.com/conda-forge/pandas-feedstock/pull/34/files#diff-e178b687b10a71a3348107ae3154e44c

Hopefully we're good now.

@conda-forge-admin, please rerender.

**Comment by jorisvandenbossche** [comment]
Should this go into a 'dev' branch instead of master?

**Comment by TomAugspurger** [comment]
I don't know. I'll wait to hear from @ocefpaf perhaps?

**Comment by jorisvandenbossche** [comment]
I just saw that is how it is done for matplotlib.

**Comment by TomAugspurger** [comment]
Or maybe @jjhelmus knows. Does the git branch matter for prerelease? I see you have a python prerelease branch here https://github.com/conda-forge/python-feedstock/tree/prerelease

**Comment by jorisvandenbossche** [comment]
No expert here, but I suppose a possible reason to use a different branch is that it might be cleaner to have the changes related to the fact it is a dev/prerelease release (eg the channel where to upload) in a separate branch, so you don't need to always add/remove this again on master.

**Comment by TomAugspurger** [comment]
That seems the most sensible. I'm going to make a PR now against a dev branch. I'm also building linux and mac conda packages locally and will upload them to our channel in the meantime so we can get something out there for people to test with.

**Comment by jjhelmus** [comment]
The conda-forge build logic does not require that pre-releases be done in a particular branch.  Whatever branching model you feel is most appropriate will work.  I like having a separate branch for these types of releases so that the `conda-forge.yml` file is only modified once, but this is just a personal preference.

**Comment by TomAugspurger** [comment]
K, let's just merge this then, and I'll revert the changes to the `conda-forge.yml`  when we do the main release.

Thanks @jjhelmus.

**Pull request merged**
