### PR TITLE
Release 0.19.0

### PR DESCRIPTION
**Pull request by jorisvandenbossche**

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
@ocefpaf @msarahan the linux build on CircleCI fails at end with:

```

Using Anaconda API: https://api.anaconda.org
Traceback (most recent call last):
  File "/feedstock_root/ci_support/upload_or_check_non_existence.py", line 124, in <module>
    main()
  File "/feedstock_root/ci_support/upload_or_check_non_existence.py", line 104, in main
    exists = built_distribution_already_exists(cli, meta, owner)
  File "/feedstock_root/ci_support/upload_or_check_non_existence.py", line 24, in built_distribution_already_exists
    fname = bldpkg_path(meta)
TypeError: bldpkg_path() missing 1 required positional argument: 'config'

./ci_support/run_docker_build.sh returned exit code 1
```

Is that something to worry about? (I would expect that it does not upload in any case on a PR, but it fails to upload on master as well, that is of course a problem)

**Comment by ocefpaf** [comment]
I am traveling with limited internet but that looks the conda-inspect
failure. Just comment that test out until conda-forge updates to
conda-build 2.

**Comment by jorisvandenbossche** [comment]
I did comment that out (before I got another error message related to the linking), but so now still an error message related to uploading

**Comment by ocefpaf** [comment]
I'll be back next Tuesday and I can take a better look then  (only phone
and 3g until then).

Btw did you try rerendering? You'll need to install conda-smithy and type
'conda smithy rerender' from the feedstock root.

**Comment by jorisvandenbossche** [comment]
Aha, rerendering seems to do the trick. Thanks!

**Comment by ocefpaf** [comment]
Awesome. Do you have merge rights? If not I can merge this for you.

On Oct 2, 2016 3:32 PM, "Joris Van den Bossche" <notifications@github.com>
wrote:

Aha, rerendering seems to do the trick. Thanks!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/conda-forge/pandas-feedstock/pull/9#issuecomment-250986897>,
or mute the thread

**Pull request merged**
