### PR TITLE
Try to build ppc64le natively

### PR DESCRIPTION
**Pull request by lithomas1**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by lithomas1** [comment]
@conda-forge-admin please rerender

**Comment by lithomas1** [comment]
@conda-forge-admin please rerender

**Comment by h-vetinari** [comment]
I don't think it has something to do with native vs. cross-compilation. From the last run on main
```
import: 'pandas'
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/pandas_1693426004477/test_tmp/run_test.py", line 2, in <module>
    import pandas
  File "$PREFIX/lib/python3.10/site-packages/pandas/__init__.py", line 46, in <module>
    from pandas.core.api import (
  File "$PREFIX/lib/python3.10/site-packages/pandas/core/api.py", line 1, in <module>
    from pandas._libs import (
  File "$PREFIX/lib/python3.10/site-packages/pandas/_libs/__init__.py", line 16, in <module>
    import pandas._libs.pandas_parser  # noqa: E501 # isort: skip # type: ignore[reportUnusedImport]
ModuleNotFoundError: No module named 'pandas._libs.pandas_parser'
```

That sounds like for some reason, that module does not get compiled on ppc...?

**Comment by lithomas1** [comment]
> I don't think it has something to do with native vs. cross-compilation. From the last run on main
> 
> ```
> import: 'pandas'
> Traceback (most recent call last):
>   File "/home/conda/feedstock_root/build_artifacts/pandas_1693426004477/test_tmp/run_test.py", line 2, in <module>
>     import pandas
>   File "$PREFIX/lib/python3.10/site-packages/pandas/__init__.py", line 46, in <module>
>     from pandas.core.api import (
>   File "$PREFIX/lib/python3.10/site-packages/pandas/core/api.py", line 1, in <module>
>     from pandas._libs import (
>   File "$PREFIX/lib/python3.10/site-packages/pandas/_libs/__init__.py", line 16, in <module>
>     import pandas._libs.pandas_parser  # noqa: E501 # isort: skip # type: ignore[reportUnusedImport]
> ModuleNotFoundError: No module named 'pandas._libs.pandas_parser'
> ```
> 
> That sounds like for some reason, that module does not get compiled on ppc...?

I downloaded the built artifact and the ``pandas_parser`` so file looks like its in the right place.

The rc also built successfully too ...

**Pull request closed without merging**
