### PR TITLE
Rls 0.25.0rc0

### PR DESCRIPTION
**Pull request by TomAugspurger**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
The windows ones are failing on an invalid directory name that has "py>=35" in it. So it seems you can't specify the python dependency like that.

**Comment by jorisvandenbossche** [comment]
Looking in the IPython recipe, which is also py3 only, they do:

https://github.com/conda-forge/ipython-feedstock/blob/b2986a9721755b4c32d36a06324975bde687421f/recipe/meta.yaml#L14

See also docs here: https://conda-forge.org/docs/maintainer/adding_pkgs.html#skipping-builds

**Comment by TomAugspurger** [comment]
I thought that restricting python was the preferred way, but is that only for noarch builds?

**Comment by ocefpaf** [comment]
> I thought that restricting python was the preferred way, but is that only for noarch builds?

It is. Can you try `python >=3.5` instead of the `python >=3.5.3`? Also, it may be a conda-build problem.

PS: we removed all `conda-build 1.18.x` series due to a bug but we are subject to the old `1.17.x` series bugs and lack of modern features :-(

**Comment by TomAugspurger** [comment]
Thanks Filipe, trying that.

**Comment by ocefpaf** [comment]
@TomAugspurger sorry. I was too quick. That **is** the preferred way for `noarch`. I totally forgot that this is not `noarch`.

**Comment by TomAugspurger** [comment]
Ah ok. I'll revert it then.

**Comment by TomAugspurger** [comment]
Hmm @ocefpaf it looks like the release-candidate stuff didn't work. These packages were released into the main label: https://anaconda.org/conda-forge/pandas/files?version=0.25.0rc0

Could we delete those packages? And I'll submit another PR with fixed labels.

**Comment by ocefpaf** [comment]
I moved them to the `rc` label. Sending a PR to fix that in a moment. Hold on.

**Comment by TomAugspurger** [comment]
Oh, changing the label is even better. Thanks!

**Pull request merged**
