### PR TITLE
RLS 1.0.0rc0

### PR DESCRIPTION
**Pull request by TomAugspurger**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by TomAugspurger** [comment]
It seems like 3.8 packages weren't built.

**Comment by ocefpaf** [comment]
You need this file and then re-render:

https://github.com/conda-forge/pandas-feedstock/blob/9789a44f93ad599ecff8ea965a60d24389da94db/.ci_support/migrations/python38.yaml

**Comment by WillAyd** [comment]
@ocefpaf should we remove 27 from that file?

**Comment by ocefpaf** [comment]
BTW maybe we should end the py38 migration so a simple re-render would suffice. What do you think @CJ-Wright?

**Comment by TomAugspurger** [comment]
Thanks Filipe, added that, will see if it works.

We shouldn't need to remove 27 there, since we have a skip for 27 in our meta.yaml

**Comment by TomAugspurger** [comment]
I'm not seeing a build for 38 on https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=109569&view=results, so I'm going to do a bit of surgery on this branch. Basically going to reset to upstream/master, and then apply the changes to conda-forge.yml and the meta.yaml.

**Comment by TomAugspurger** [comment]
@conda-forge-admin rerender

**Comment by CJ-Wright** [comment]
We could end it, I think the largest outstanding package is numba. One thing we could consider is to update the python version in the global pinning but leave the migration going. That way downstream pacakges get the PRs, in the case that they haven't gotten an upgraded by a version bump or manually.

**Comment by TomAugspurger** [comment]
Welp, I messed that up :smile: I'll come back to this a little later.

**Comment by TomAugspurger** [comment]
Hmm, I'm only seeing linux packages for the RC on https://anaconda.org/conda-forge/pandas/files?version=1.0.0rc0. In https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=109647&view=logs&j=a8dee1cf-d17f-5cb0-b53f-4a93dfdbfb0c&t=24d63578-22bc-579d-8e8e-d8ed81a92178 (mac, py38) I see

```
Distribution /usr/local/miniconda/conda-bld/osx-64/pandas-1.0.0rc0-py38h4f17bb1_0.tar.bz2 is new for conda-forge, but no upload is taking place because the BINSTAR_TOKEN is missing.
```

**Comment by TomAugspurger** [comment]
Maybe that makes sense, if it's the PR build. So perhaps we just didn't get a CI build after merging?

**Comment by TomAugspurger** [comment]
@ocefpaf do you know if azure pipelines is configured to only build on the `master` branch, and not the `dev` branch?

**Comment by ocefpaf** [comment]
> @ocefpaf do you know if azure pipelines is configured to only build on the `master` branch, and not the `dev` branch?

Nope. It should work. Investigating...

**Comment by CJ-Wright** [comment]
maybe this needs https://conda-forge.org/docs/maintainer/conda_forge_yml.html#upload-on-branch

**Comment by ocefpaf** [comment]
> maybe this needs [conda-forge.org/docs/maintainer/conda_forge_yml.html#upload-on-branch](https://conda-forge.org/docs/maintainer/conda_forge_yml.html#upload-on-branch)

When did that change landed! I missed and it probably broke a lot of rc releases on branches.

**Comment by CJ-Wright** [comment]
https://github.com/conda-forge/conda-smithy/pull/1108

I thought it was backwards compat

**Comment by TomAugspurger** [comment]
@ocefpaf thanks for getting the packages up (if it was you who did it).

@CJ-Wright do you think the fact that only the aaarch64 packages were uploaded is a bug? It seems like drone.io and the other CI services didn't behave the same (though I'm not sure what the expected behavior is here).

**Comment by CJ-Wright** [comment]
I have no idea

**Comment by ocefpaf** [comment]
> @ocefpaf thanks for getting the packages up (if it was you who did it).

I restarted the CIs.

> @CJ-Wright do you think the fact that only the aaarch64 packages were uploaded is a bug? It seems like drone.io and the other CI services didn't behave the same (though I'm not sure what the expected behavior is here).

I don't think this is related to what CJ mentioned above b/c the change should not affect existing feedstocks, or we should be seeing way more breakages,

**Pull request merged**
